#!/usr/bin/env bash
# brief-absolute-paths.test.sh — FAIL-ON-REVERT hermetic tests for BRIEF-ABSOLUTE-PATHS.
#
# (a) The rendered brief contains an absolute judgment path and NO unexpanded $FLEET/$DROID/$id.
#     Revert the interpolation -> RED.
# (b) A judgment file written to the rendered absolute path IS picked up by emit_session_report
#     and its 5 fields land in the report (not NOT-REPORTED).
# (c) Simulate the failure: run the brief's instruction from a DIFFERENT CWD with $FLEET unset
#     and prove the file still lands in the right place. This is the case that actually broke;
#     a test that does not reproduce it proves nothing.
# (d) ANTI-OVER-BLOCK: an absent judgment file still yields NOT-REPORTED as designed.
#
# Run:  bash fleet/tests/brief-absolute-paths.test.sh   (exit 0 = all pass)
set -uo pipefail
# shellcheck disable=SC2016,SC2034
# SC2016: single-quoted $VAR strings are intentional grep patterns in has()/no()
# SC2034: FLEET/DROID/id set before function call are consumed by render_join_prompt
SRC="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PASS=0; FAIL=0
ok(){   PASS=$((PASS+1)); echo "PASS: $1"; }
bad(){  FAIL=$((FAIL+1)); echo "FAIL: $1"; }
has(){  printf '%s' "$1" | grep -qF -- "$2" && ok "$3" || bad "$3 (missing '$2')"; }
no(){   printf '%s' "$1" | grep -qF -- "$2" && bad "$3 (unexpected '$2')" || ok "$3"; }
check(){ [ "$2" = "$3" ] && ok "$1" || bad "$1 (expected '$3', got '$2')"; }

# ── Extract render_join_prompt ──────────────────────────────────────────────────────────────────
EXTRACT_RENDER="$(mktemp)"
{
  echo "# AUTOGENERATED test helper — DO NOT EDIT."
  awk '
    /^  render_join_prompt\(\) \{$/ { in_fn=1; print; next }
    in_fn && /^  \}$/ { print; in_fn=0; exit }
    in_fn { print }
  ' "$SRC/fleet-droid.sh"
} > "$EXTRACT_RENDER"
# shellcheck source=/dev/null
. "$EXTRACT_RENDER"
if ! declare -F render_join_prompt >/dev/null; then
  echo "FAIL: render_join_prompt was not extractable from fleet-droid.sh — the function is missing." >&2
  exit 1
fi

# ── Extract emit_session_report ─────────────────────────────────────────────────────────────────
EXTRACT_EMIT="$(mktemp)"
{
  echo "# AUTOGENERATED test helper — DO NOT EDIT."
  awk '
    /^emit_session_report\(\)\{$/ { in_fn=1; print; next }
    in_fn && /^\}$/ { print; in_fn=0; exit }
    in_fn { print }
  ' "$SRC/fleet-droid.sh"
} > "$EXTRACT_EMIT"
# shellcheck source=/dev/null
. "$EXTRACT_EMIT"
if ! declare -F emit_session_report >/dev/null; then
  echo "FAIL: emit_session_report was not extractable from fleet-droid.sh — the wire is missing." >&2
  exit 1
fi

# ── mk_fixture <tmpdir> — stand up a minimal temp git repo + worktree ────────────────────────────
mk_fixture(){
  local d="$1"
  local R="$d/repo" WT="$d/wt" BR="feat/bap-$RANDOM"
  git init -q -b master "$R"
  git -C "$R" config user.email bap@test; git -C "$R" config user.name bap
  echo "base" > "$R/README.md"
  git -C "$R" add README.md; git -C "$R" commit -qm base
  git -C "$R" worktree add -b "$BR" "$WT" master >/dev/null 2>&1
  echo "edit" >> "$WT/README.md"
  git -C "$WT" add README.md; git -C "$WT" commit -qm "edit"
  echo "$R|$WT|$BR|master"
}

# ═══════════════════════════════════════════════════════════════════════════════════════════════════
echo "== (a) rendered brief has absolute judgment path, no unexpanded \$FLEET / \$DROID / \$id =="
# Sweep the real JOIN-PROMPT.md for $VAR instances the model cannot expand. This is done once
# against the REAL file (not a mock) so the sweep is factual.
REAL_JOIN="$SRC/JOIN-PROMPT.md"
SWEEP_HITS=0
while IFS= read -r line; do
  case "$line" in
    *\$FLEET*)  echo "  SWEEP-HIT: \$FLEET  on line: $line"; SWEEP_HITS=$((SWEEP_HITS+1)) ;;
    *\$DROID*)  echo "  SWEEP-HIT: \$DROID  on line: $line"; SWEEP_HITS=$((SWEEP_HITS+1)) ;;
    *\$id*)     echo "  SWEEP-HIT: \$id     on line: $line"; SWEEP_HITS=$((SWEEP_HITS+1)) ;;
  esac
done < "$REAL_JOIN"
check "a0 sweep: exactly 1 line with \$FLEET/\$DROID/\$id (the judgment path)" "$SWEEP_HITS" "1"
if [ "$SWEEP_HITS" -ne 1 ]; then
  echo "  Sweep found $SWEEP_HITS lines with \$VAR; expected exactly 1 (the judgment path line)."
  echo "  Fix or ticket every additional instance."
fi

# ── (a1–a4): mock render and verify ──
d="$(mktemp -d)"
MOCK_FLEET="$d/fleet_dir"
MOCK_DROID="economy-42"
MOCK_ID="TEST-A"
mkdir -p "$MOCK_FLEET"
# Minimal JOIN-PROMPT.md with the exact same pattern as the real file
cat > "$MOCK_FLEET/JOIN-PROMPT.md" <<'EOF'
You are a Charon build droid in ROBOT MODE.

You only fill in 5 JUDGMENT fields. Before you exit, write a partial block to:
    $FLEET/state/judgment/$DROID-$id.md
containing exactly these five lines:
    OBSERVABLE:   MET | DEFERRED
    RAN:          what you proved
    READ:         what you concluded
    BRIEF-ERRORS: none | what the brief got wrong
    NEXT:         the single thing the manager should do next
EOF

FLEET="$MOCK_FLEET" DROID="$MOCK_DROID" id="$MOCK_ID" rendered="$(render_join_prompt)"
EXPECTED_PATH="$MOCK_FLEET/state/judgment/$MOCK_DROID-$MOCK_ID.md"
has "$rendered" "$EXPECTED_PATH" "a1 absolute judgment path rendered in brief"
no "$rendered" '$FLEET' "a2 no unexpanded \$FLEET in rendered brief"
no "$rendered" '$DROID' "a3 no unexpanded \$DROID in rendered brief"
no "$rendered" '$id'    "a4 no unexpanded \$id in rendered brief"
rm -rf "$d"

# ═══════════════════════════════════════════════════════════════════════════════════════════════════
echo "== (b) judgment file at rendered absolute path IS picked up by emit_session_report =="
d2="$(mktemp -d)"
IFS='|' read -r R2 WT2 BR2 BASE2 <<<"$(mk_fixture "$d2")"
OUTLOG2="$d2/outlog.txt"
printf '%s\n' "CHARON_RUN_RESULT=SUCCESS" "CHARON_RUN_RESULT_FIRST_MODEL=minimax-m3-free" > "$OUTLOG2"
mkdir -p "$d2/state/judgment"
cat > "$d2/state/judgment/strong-88-TEST-B.md" <<'JUDGMENT'
OBSERVABLE:   MET — gateway confirmed
RAN:          pytest -q green
READ:         changelog diff vs master
BRIEF-ERRORS: none
NEXT:         merge the PR
JUDGMENT
block_b="$(FLEET="$d2" emit_session_report "TEST-B" "strong-88" "$BR2" "$WT2" "$R2" "$BASE2" \
              "minimax-m3-free" "SUCCESS" "0" "README.md" "DONE" "$OUTLOG2")"
has "$block_b" "OBSERVABLE:   MET — gateway confirmed"  "b1 judgment file picked up — OBSERVABLE"
has "$block_b" "RAN:          pytest -q green"           "b2 judgment file picked up — RAN"
has "$block_b" "READ:         changelog diff vs master"  "b3 judgment file picked up — READ"
has "$block_b" "BRIEF-ERRORS: none"                       "b4 judgment file picked up — BRIEF-ERRORS"
has "$block_b" "NEXT:         merge the PR"               "b5 judgment file picked up — NEXT"
rm -rf "$d2"

# ═══════════════════════════════════════════════════════════════════════════════════════════════════
echo "== (c) simulate the failure: different CWD + \$FLEET unset, file still lands at absolute path =="
d3="$(mktemp -d)"
ALT_CWD="$d3/random-working-directory"
mkdir -p "$ALT_CWD"
JUDGMENT_DIR="$d3/fleet/state/judgment"
mkdir -p "$JUDGMENT_DIR"
JUDGMENT_FILE="$JUDGMENT_DIR/some-droid-TEST-C.md"

# Simulate the model's shell: $FLEET and $DROID are UNSET, CWD is not the fleet directory.
# The brief TELLS the model to write to the ABSOLUTE path (rendered by the launcher).
# If the path were relative or depended on $FLEET, this would fail.
(
  unset FLEET DROID id 2>/dev/null || true
  cd "$ALT_CWD" || exit 1
  printf '%s\n' "OBSERVABLE:   MET" "RAN:          test" "READ:         test" \
    "BRIEF-ERRORS: none" "NEXT:         merge" > "$JUDGMENT_FILE"
)
[ -f "$JUDGMENT_FILE" ] && ok "c1 judgment file at absolute path survives \$FLEET unset + different CWD" \
  || bad "c1 judgment file MISSING — \$FLEET unset caused relative resolution (bug reproduced)"
# The file must NOT exist relative to CWD
relative_file="$ALT_CWD/state/judgment/some-droid-TEST-C.md"
[ -f "$relative_file" ] && bad "c2 file landed relative to CWD (bug reproduced — path was relative)" \
  || ok "c2 file did NOT land relative to CWD (absolute path worked)"
rm -rf "$d3"

# ═══════════════════════════════════════════════════════════════════════════════════════════════════
echo "== (d) ANTI-OVER-BLOCK: absent judgment file -> NOT-REPORTED =="
d4="$(mktemp -d)"
IFS='|' read -r R4 WT4 BR4 BASE4 <<<"$(mk_fixture "$d4")"
OUTLOG4="$d4/outlog.txt"
printf '%s\n' "CHARON_RUN_RESULT=SUCCESS" "CHARON_RUN_RESULT_FIRST_MODEL=minimax-m3-free" > "$OUTLOG4"
# NO judgment file written — model produced nothing. All 5 fields must be NOT-REPORTED.
block_d="$(FLEET="$d4" emit_session_report "TEST-D" "strong-99" "$BR4" "$WT4" "$R4" "$BASE4" \
              "minimax-m3-free" "SUCCESS" "0" "README.md" "DONE" "$OUTLOG4")"
has "$block_d" "OBSERVABLE:   NOT-REPORTED" "d1 absent judgment file -> OBSERVABLE=NOT-REPORTED"
has "$block_d" "RAN:          NOT-REPORTED" "d2 absent judgment file -> RAN=NOT-REPORTED"
has "$block_d" "READ:         NOT-REPORTED" "d3 absent judgment file -> READ=NOT-REPORTED"
has "$block_d" "BRIEF-ERRORS: NOT-REPORTED" "d4 absent judgment file -> BRIEF-ERRORS=NOT-REPORTED"
has "$block_d" "NEXT:         NOT-REPORTED" "d5 absent judgment file -> NEXT=NOT-REPORTED"
rm -rf "$d4"

# ── Cleanup ──────────────────────────────────────────────────────────────────────────────────────
rm -f "$EXTRACT_RENDER" "$EXTRACT_EMIT"

echo
echo "--- brief-absolute-paths: $PASS passed, $FAIL failed ---"
[ "$FAIL" -eq 0 ] || exit 1
echo "ALL BRIEF-ABSOLUTE-PATHS TESTS PASS"
