#!/usr/bin/env bash
# session-report-wire.test.sh — FAIL-ON-REVERT tests for the SESSION-REPORT-WIRE.
#
# (a) droid emits NO report -> a COMPLETE v1 block still exists with the 5 judgment fields as
#     `NOT-REPORTED`. Validated by check-session-report.sh (FAIL-LOUD: names missing fields).
# (b) derived COMMIT/FILES/GATE match git + the real gate exit code — REVERT the derivation
#     (hardcode GATE: PASS) and this test goes RED (proves the field is derived, not echoed).
# (c) model emits STATUS: DONE while the gate exit code is non-zero -> BOTH recorded and a
#     MODEL-LIE-FLAG line is appended (silently overwriting either side is RED).
# (d) report lands at $FLEET/state/reports/<droid>-<ticket>.md AND the function echoes the
#     same block to stdout (the caller appends it to the PR body).
# (e) ANTI-OVER-BLOCK: a droid that emits a FULL valid v1 block keeps its judgment fields
#     verbatim — the launcher does NOT clobber them; both blocks live in the report file.
#
# Strategy: extract the inline `emit_session_report` function from fleet-droid.sh (lines 651-849
# of the current build) into a hermetic test harness. The harness is fed a real temp git repo +
# worktree + outlog + judgment file so EVERY branch of the derivation runs against real git/awk.
# We NEVER touch the live fleet/state (mktemp -d, hermetic).
#
# Run:  bash fleet/tests/session-report-wire.test.sh   (exit 0 = all pass)
set -uo pipefail
SRC="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"   # the real fleet/ dir
PASS=0; FAIL=0
ok(){   PASS=$((PASS+1)); echo "PASS: $1"; }
bad(){  FAIL=$((FAIL+1)); echo "FAIL: $1"; }
has(){  printf '%s' "$1" | grep -qF -- "$2" && ok "$3" || bad "$3 (missing '$2')"; }
no(){   printf '%s' "$1" | grep -qF -- "$2" && bad "$3 (unexpected '$2')" || ok "$3"; }
check(){ [ "$2" = "$3" ] && ok "$1" || bad "$1 (expected '$3', got '$2')"; }

# Extract the inline function from fleet-droid.sh into a sourced helper. This avoids sourcing
# the whole launcher (which would set up traps + claim loops). FAIL LOUD if the function is
# missing — that catches a refactor that removes it.
EXTRACT_HELPER="$(mktemp)"
{
  echo "# AUTOGENERATED test helper — DO NOT EDIT."
  # The function body is bounded by `emit_session_report(){` and the next line that is just `}`.
  awk '
    /^emit_session_report\(\)\{$/ { in_fn=1; print; next }
    in_fn && /^\}$/ { print; in_fn=0; exit }
    in_fn { print }
  ' "$SRC/fleet-droid.sh"
} > "$EXTRACT_HELPER"
# shellcheck source=/dev/null
. "$EXTRACT_HELPER"
# Sanity: confirm extraction worked. If this fails, fleet-droid.sh no longer defines the function
# — the wire is gone, and the whole point of the ticket has been reverted.
if ! declare -F emit_session_report >/dev/null; then
  echo "FAIL: emit_session_report was not extractable from fleet-droid.sh — the wire is missing." >&2
  echo "      grep '^emit_session_report' $SRC/fleet-droid.sh (function name regression)" >&2
  exit 1
fi

# mk_fixture <label> — stand up a real temp git repo with an initial commit on master, a worktree
# branch, and a single file change. Echoes "<tmpdir>|<repo>|<wt>|<branch>|<base_ref>".
mk_fixture(){
  local d; d="$(mktemp -d)"
  local R="$d/repo" WT="$d/wt" BR="feat/sr-test-$RANDOM"
  git init -q -b master "$R"
  git -C "$R" config user.email sr@test; git -C "$R" config user.name sr
  echo "base" > "$R/README.md"
  git -C "$R" add README.md; git -C "$R" commit -qm base
  # Branch the worktree off master.
  git -C "$R" worktree add -b "$BR" "$WT" master >/dev/null 2>&1
  # One realistic edit on the worktree's branch + commit it.
  echo "edit" >> "$WT/README.md"
  git -C "$WT" add README.md; git -C "$WT" commit -qm "edit: change readme"
  echo "$d|$R|$WT|$BR|master"
}

# write_outlog <wt> <content...> — write a fake model transcript (named after the worktree so the
# function reads its own back). The outlog records charon-run.sh's own CHARON_RUN_RESULT lines so
# the function's parser finds them.
write_outlog(){
  local out="$1"; shift
  printf '%s\n' "$@" > "$out"
}

# ────────────────────────────────────────────────────────────────────────────────────────────
echo "== (a) NO report emitted by model -> complete v1 block still exists, judgment fields = NOT-REPORTED =="
# Setup: clean repo, no judgment file written (the model emitted nothing).
IFS='|' read -r d R WT BR BASE <<<"$(mk_fixture)"
OUTLOG="$d/outlog.txt"
write_outlog "$OUTLOG" \
  "CHARON_RUN_RESULT=SUCCESS model=minimax-m3-free" \
  "CHARON_RUN_RESULT_FIRST_MODEL=minimax-m3-free"
# Run the function with a GREEN gate (0) and DONE status. No judgment file = NOT-REPORTED on the
# 5 judgment fields. FLEET is pointed at the temp dir so the report lands under the fixture.
block_a="$(FLEET="$d" emit_session_report "T-A" "frontier-99" "$BR" "$WT" "$R" "$BASE" \
              "minimax-m3-free" "SUCCESS" "0" "README.md" "DONE" "$OUTLOG")"
report_a="$d/state/reports/frontier-99-T-A.md"
# (a1) the file landed at the canonical path.
[ -f "$report_a" ] && ok "a1 report lands at state/reports/<droid>-<ticket>.md" \
                    || bad "a1 report did NOT land at state/reports/<droid>-<ticket>.md (path: $report_a)"
# (a2) the block has every required field (validator exits 0). This is the FAIL-LOUD check the
# ticket contract demands — a missing field REDs the gate, not silently passes.
validator_out="$(bash "$SRC/check-session-report.sh" "$report_a" 2>&1)"; validator_rc=$?
check "a2 check-session-report.sh exits 0 on launcher-derived block" "$validator_rc" "0"
[ "$validator_rc" -eq 0 ] && has "$validator_out" "OK" "a3 validator reports OK on launcher block"
# (a4-a8) the 5 judgment fields are NOT-REPORTED (since the model wrote nothing).
has "$block_a" "OBSERVABLE:   NOT-REPORTED" "a4 OBSERVABLE=NOT-REPORTED when model emitted nothing"
has "$block_a" "RAN:          NOT-REPORTED" "a5 RAN=NOT-REPORTED when model emitted nothing"
has "$block_a" "READ:         NOT-REPORTED" "a6 READ=NOT-REPORTED when model emitted nothing"
has "$block_a" "BRIEF-ERRORS: NOT-REPORTED" "a7 BRIEF-ERRORS=NOT-REPORTED when model emitted nothing"
has "$block_a" "NEXT:         NOT-REPORTED" "a8 NEXT=NOT-REPORTED when model emitted nothing"
# (a9) TICKET field is the droid's own fact (the id), NOT echoed from the model.
has "$block_a" "TICKET:       T-A" "a9 TICKET field derived from launcher (id='T-A'), not from model"
# (a10) the derived GATE field reflects the launcher's REAL exit code (we passed 0 -> PASS).
has "$block_a" "GATE:         PASS" "a10 GATE=PASS derived from launcher exit code (gate_exit=0)"
rm -rf "$d"

# ────────────────────────────────────────────────────────────────────────────────────────────
echo "== (b) derived GATE/COMMIT/FILES match git + the real gate exit code =="
# The test that catches a hardcoded 'GATE: PASS' (or any other derivation revert): the field
# is computed FROM $9 (gate_exit), so a non-zero exit produces FAIL.
IFS='|' read -r d R WT BR BASE <<<"$(mk_fixture)"
OUTLOG="$d/outlog.txt"
write_outlog "$OUTLOG" \
  "CHARON_RUN_RESULT=SUCCESS model=minimax-m3-free" \
  "CHARON_RUN_RESULT_FIRST_MODEL=minimax-m3-free"
# Run with gate_exit=1 — GATE MUST read as FAIL.
block_b="$(FLEET="$d" emit_session_report "T-B" "strong-77" "$BR" "$WT" "$R" "$BASE" \
              "minimax-m3-free" "SUCCESS" "1" "README.md" "DONE" "$OUTLOG")"
# (b1) derived GATE field carries the launcher's exit code (1 -> FAIL).
has "$block_b" "GATE:         FAIL — gate exit code 1" "b1 GATE: FAIL is derived from gate_exit=1 (not hardcoded PASS)"
no  "$block_b" "GATE:         PASS" "b2 GATE: PASS is NOT echoed when the real exit code is 1"
# (b3) derived COMMIT field is the worktree's real HEAD sha (a 40-char hex).
commit_field="$(printf '%s\n' "$block_b" | awk -F': ' '$1=="COMMIT"{sub(/^[^:]*: +/, "");print;exit}')"
# Use bash pattern matching (case) instead of `[0-9a-f]\{40\}` — backslashes inside `case` glob
# patterns don't behave the same as in extended regex, so a POSIX-equivalent check via `tr` is
# more portable and unambiguous: 40 chars, all hex.
case "$commit_field" in
  *[!0-9a-fA-F]*) bad "b3 COMMIT field has non-hex characters: '$commit_field'" ;;
  *)
    if [ "${#commit_field}" -eq 40 ]; then
      ok "b3 COMMIT field is the real worktree HEAD sha ($commit_field, 40 hex chars)"
    else
      bad "b3 COMMIT field is not 40 chars: '$commit_field' (length ${#commit_field})"
    fi
    ;;
esac
# (b4) derived FILES count + paths match `git diff --name-only master..$branch`.
expected_n_files="$(git -C "$WT" diff --name-only "$BASE..$BR" 2>/dev/null | wc -l | tr -d ' ')"
files_field="$(printf '%s\n' "$block_b" | awk -F': ' '$1=="FILES"{sub(/^[^:]*: +/, "");print;exit}')"
files_count="$(printf '%s' "$files_field" | awk '{print $1}')"
check "b4 FILES count matches git-diff-name-only" "$files_count" "$expected_n_files"
has "$files_field" "README.md" "b5 FILES paths include the changed file (README.md)"
# (b6) OWNS-OK validates the diff against the ticket's owns: list. README.md is in owns -> yes.
has "$block_b" "OWNS-OK:      yes" "b6 OWNS-OK: yes when all changed paths are in owns:"
rm -rf "$d"

# ────────────────────────────────────────────────────────────────────────────────────────────
echo "== (b.revert) hardcode 'GATE: PASS' in the function body -> this test goes RED =="
# This is the FAIL-ON-REVERT assertion: open fleet-droid.sh, replace the gate-derivation branch
# with `local f_gate="PASS"`, run this test — b.revert (and b1, b2) flip to BAD. That's the
# red the ticket contract demands.
grep_src="$(mktemp)"
awk '
  /^emit_session_report\(\)\{$/ { in_fn=1 }
  in_fn { print }
  in_fn && /^\}$/ { in_fn=0; exit }
' "$SRC/fleet-droid.sh" > "$grep_src"
# Confirm the function body still computes f_gate from $gate_exit. A revert that hardcodes PASS
# removes the `if [ "$gate_exit" -eq 0 ]` branch — this assertion flips to RED on that revert.
if grep -q 'f_gate="FAIL — gate exit code' "$grep_src"; then
  ok "b.revert1 f_gate is computed from \$gate_exit (FAIL branch present, hardcoded-PASS revert is detectable)"
else
  bad "b.revert1 f_gate is NOT computed from \$gate_exit — gate field is hardcoded, derivation is reverted"
fi
if grep -qE 'local f_gate="PASS"' "$grep_src"; then
  bad "b.revert2 f_gate is hardcoded 'PASS' — ticket contract violated (GATE field no longer DERIVED from the real exit code)"
else
  ok "b.revert2 f_gate is NOT hardcoded 'PASS' (real derivation in place)"
fi
rm -f "$grep_src"

# ────────────────────────────────────────────────────────────────────────────────────────────
echo "== (c) model self-reports STATUS: DONE while gate exit code is non-zero -> BOTH kept + conflict =="
IFS='|' read -r d R WT BR BASE <<<"$(mk_fixture)"
OUTLOG="$d/outlog.txt"
# The outlog BOTH has charon-run.sh's own status line AND a complete v1 block whose STATUS is
# DONE — the classic self-report-lie pattern. CHARON_RUN_RESULT_FIRST_MODEL is present so the
# session line parses.
write_outlog "$OUTLOG" \
  "CHARON_RUN_RESULT=SUCCESS model=minimax-m3-free" \
  "CHARON_RUN_RESULT_FIRST_MODEL=minimax-m3-free" \
  "" \
  "=== SESSION REPORT v1 ===" \
  "TICKET:       T-C" \
  "SESSION:      strong-55 | minimax-m3-free" \
  "STATUS:       DONE" \
  "COMMIT:       deadbeef" \
  "FILES:        1 changed: README.md" \
  "OWNS-OK:      yes" \
  "GATE:         PASS" \
  "TESTS:        3 passed" \
  "RED-PROOF:    broken=1 green=0" \
  "OBSERVABLE:   MET" \
  "RAN:          ran pytest" \
  "READ:         read gate output" \
  "BRIEF-ERRORS: none" \
  "BLOCKED-BY:   none" \
  "BUDGET:       ok" \
  "NEXT:         merge" \
  "=== END REPORT ==="
# The launcher passes gate_exit=1 (REAL failure) but the model claims GATE: PASS + STATUS: DONE.
block_c="$(FLEET="$d" emit_session_report "T-C" "strong-55" "$BR" "$WT" "$R" "$BASE" \
              "minimax-m3-free" "SUCCESS" "1" "README.md" "DONE" "$OUTLOG")"
report_c="$d/state/reports/strong-55-T-C.md"
# (c1) derived STATUS=BLOCKED — wait, the launcher's call was `STATUS=DONE`, so the derived line
# is DONE. The CONFLICT line is what catches the lie. Both are present.
has "$block_c" "STATUS:       DONE" "c1 launcher's derived STATUS is the passed-in value (DONE)"
# (c2) GATE field reads FAIL — derived from gate_exit=1 (NOT echoed from the model).
has "$block_c" "GATE:         FAIL — gate exit code 1" "c2 GATE field derives from gate_exit=1, not the model's PASS claim"
# (c3) the model's self-report block is KEPT verbatim (not clobbered).
has "$block_c" "--- MODEL SELF-REPORT BLOCK (kept verbatim; NOT-REPORTED-safe) ---" "c3 model block is kept verbatim"
has "$block_c" "STATUS:       DONE" "c4 the model's STATUS: DONE appears in the kept block"
has "$block_c" "GATE:         PASS" "c5 the model's GATE: PASS appears in the kept block"
# (c6) conflict flag is appended when the model status disagrees with the derived status. In this
# case both STATUS fields say DONE — STATUS doesn't trigger the flag. The disagreement here is
# between the derived GATE (FAIL) and the model's GATE (PASS), which the format spec considers
# the highest-value signal. We surface it via a MODEL-LIE-FLAG line. Verify a flag is present
# that names the GATE discrepancy.
has "$block_c" "MODEL-LIE-FLAG:" "c6 MODEL-LIE-FLAG appended when model block contradicts derived facts"
# (c7) the validator still passes — both blocks together cover every field.
bash "$SRC/check-session-report.sh" "$report_c" >/dev/null 2>&1 && ok "c7 derived block is validator-clean even with a contradicting model block alongside" \
  || bad "c7 derived block FAILS the validator — the kept model block broke field parsing"
rm -rf "$d"

# ────────────────────────────────────────────────────────────────────────────────────────────
echo "== (d) report lands at fleet/state/reports/<droid>-<ticket>.md AND echoes to stdout =="
IFS='|' read -r d R WT BR BASE <<<"$(mk_fixture)"
OUTLOG="$d/outlog.txt"
write_outlog "$OUTLOG" \
  "CHARON_RUN_RESULT=SUCCESS model=minimax-m3-free" \
  "CHARON_RUN_RESULT_FIRST_MODEL=minimax-m3-free"
block_d="$(FLEET="$d" emit_session_report "T-D" "strong-22" "$BR" "$WT" "$R" "$BASE" \
              "minimax-m3-free" "SUCCESS" "0" "README.md" "DONE" "$OUTLOG")"
# (d1) report file path is canonical: state/reports/<droid>-<ticket>.md.
report_d="$d/state/reports/strong-22-T-D.md"
[ -f "$report_d" ] && ok "d1 report file at canonical path $report_d" \
                   || bad "d1 report file missing at $report_d"
# (d2) the stdout echo is byte-equal to the file (the caller appends it to the PR body).
file_content="$(cat "$report_d")"
[ "$block_d" = "$file_content" ] && ok "d2 stdout echo == file content (callable for PR-body append)" \
                                  || bad "d2 stdout echo DIFFERS from file content (PR body would diverge)"
# (d3) a SECOND call with the same droid+id writes the same file (idempotent — a re-run
# produces a fresh report, not an accumulating mess).
block_d2="$(FLEET="$d" emit_session_report "T-D" "strong-22" "$BR" "$WT" "$R" "$BASE" \
               "minimax-m3-free" "SUCCESS" "0" "README.md" "DONE" "$OUTLOG")"
[ "$block_d" = "$block_d2" ] && ok "d3 re-run is deterministic (same inputs -> same block)" \
                              || bad "d3 re-run is NON-deterministic (same inputs -> different block)"
rm -rf "$d"

# ────────────────────────────────────────────────────────────────────────────────────────────
echo "== (e) ANTI-OVER-BLOCK: droid emits a FULL valid v1 block -> judgment fields are PRESERVED =="
IFS='|' read -r d R WT BR BASE <<<"$(mk_fixture)"
OUTLOG="$d/outlog.txt"
# Build a model outlog that emits a COMPLETE v1 block whose 5 judgment fields are NON-default
# values. A launcher that "clobbers" them by always writing NOT-REPORTED would lose these.
write_outlog "$OUTLOG" \
  "CHARON_RUN_RESULT=SUCCESS model=minimax-m3-free" \
  "CHARON_RUN_RESULT_FIRST_MODEL=minimax-m3-free" \
  "" \
  "=== SESSION REPORT v1 ===" \
  "TICKET:       T-E" \
  "SESSION:      strong-33 | minimax-m3-free" \
  "STATUS:       DONE" \
  "COMMIT:       cafebabe" \
  "FILES:        1 changed: README.md" \
  "OWNS-OK:      yes" \
  "GATE:         PASS" \
  "TESTS:        5 passed" \
  "RED-PROOF:    broken=1 green=0" \
  "OBSERVABLE:   MET — proved on live gateway" \
  "RAN:          pytest -q + ruff + mypy" \
  "READ:         changelog diff vs master" \
  "BRIEF-ERRORS: none" \
  "BLOCKED-BY:   none" \
  "BUDGET:       ok" \
  "NEXT:         merge the PR" \
  "=== END REPORT ==="
# Run with NO separate judgment file — the model's judgment fields live inside the self-report
# block, and the launcher MUST NOT clobber them.
block_e="$(FLEET="$d" emit_session_report "T-E" "strong-33" "$BR" "$WT" "$R" "$BASE" \
              "minimax-m3-free" "SUCCESS" "0" "README.md" "DONE" "$OUTLOG")"
# (e1-e5) the model's judgment fields appear VERBATIM in the kept block. If the launcher
# clobbered them with NOT-REPORTED these would be missing.
has "$block_e" "OBSERVABLE:   MET — proved on live gateway" "e1 OBSERVABLE preserved verbatim (NOT clobbered)"
has "$block_e" "RAN:          pytest -q + ruff + mypy"      "e2 RAN preserved verbatim (NOT clobbered)"
has "$block_e" "READ:         changelog diff vs master"    "e3 READ preserved verbatim (NOT clobbered)"
has "$block_e" "BRIEF-ERRORS: none"                          "e4 BRIEF-ERRORS preserved verbatim"
has "$block_e" "NEXT:         merge the PR"                  "e5 NEXT preserved verbatim"
# (e6) the validator still accepts the launcher-derived block (the 5 derived judgment fields
# stay NOT-REPORTED because the model wrote a SEPARATE v1 block, not the partial judgment file
# the JOIN-PROMPT asks for — and that's exactly what we want preserved).
report_e="$d/state/reports/strong-33-T-E.md"
bash "$SRC/check-session-report.sh" "$report_e" >/dev/null 2>&1 && ok "e6 derived block is validator-clean (anti-over-block + kept block both pass)" \
  || bad "e6 derived block FAILS the validator (anti-over-block may have corrupted field parsing)"
# (e7) judgment file absent -> derived 5 fields stay NOT-REPORTED (we did NOT write one here).
has "$block_e" "OBSERVABLE:   NOT-REPORTED" "e7 derived OBSERVABLE stays NOT-REPORTED when judgment file absent"
rm -rf "$d"

# ────────────────────────────────────────────────────────────────────────────────────────────
echo "== (e.judgment) droid writes the partial judgment FILE (JOIN-PROMPT path) -> fields land in the derived block =="
# The model's JOIN-PROMPT-shaped output: 5 fields only, NO header, NO === SESSION REPORT v1 ===
# fence, written to state/judgment/<droid>-<id>.md. The launcher reads them and puts them in
# the DERIVED block (NOT in a kept verbatim section). Verifies the wire shape the JOIN-PROMPT
# asks for actually flows through.
IFS='|' read -r d R WT BR BASE <<<"$(mk_fixture)"
OUTLOG="$d/outlog.txt"
write_outlog "$OUTLOG" \
  "CHARON_RUN_RESULT=SUCCESS model=minimax-m3-free" \
  "CHARON_RUN_RESULT_FIRST_MODEL=minimax-m3-free"
mkdir -p "$d/state/judgment"
cat > "$d/state/judgment/frontier-44-T-F.md" <<'JUDGMENT'
OBSERVABLE:   MET — live gateway proved
RAN:          pytest -q + charon.cli gate
READ:         changelog vs master
BRIEF-ERRORS: none
NEXT:         merge the PR
JUDGMENT
block_f="$(FLEET="$d" emit_session_report "T-F" "frontier-44" "$BR" "$WT" "$R" "$BASE" \
              "minimax-m3-free" "SUCCESS" "0" "README.md" "DONE" "$OUTLOG")"
# (f1-f5) judgment fields appear in the derived block, NOT as a kept verbatim section.
has "$block_f" "OBSERVABLE:   MET — live gateway proved" "f1 OBSERVABLE from judgment file lands in derived block"
has "$block_f" "RAN:          pytest -q + charon.cli gate" "f2 RAN from judgment file lands in derived block"
has "$block_f" "READ:         changelog vs master" "f3 READ from judgment file lands in derived block"
has "$block_f" "BRIEF-ERRORS: none" "f4 BRIEF-ERRORS from judgment file lands in derived block"
has "$block_f" "NEXT:         merge the PR" "f5 NEXT from judgment file lands in derived block"
no   "$block_f" "MODEL SELF-REPORT BLOCK" "f6 NO kept-verbatim section when the model writes only the judgment file (correct wire shape)"
rm -rf "$d"

# ────────────────────────────────────────────────────────────────────────────────────────────
echo "== (bypass) judgment file written BUT model is absent -> launcher reads the judgment file alone =="
# Belt-and-suspenders: when the model wrote the judgment file but the outlog doesn't have a v1
# block, the launcher derives everything else and reads the judgment file. Nothing in the
# derived block names a "MODEL SELF-REPORT" section.
IFS='|' read -r d R WT BR BASE <<<"$(mk_fixture)"
OUTLOG="$d/outlog.txt"
# Minimal outlog (no v1 block at all, no CHARON_RUN_RESULT_FIRST_MODEL line).
write_outlog "$OUTLOG" "CHARON_RUN_RESULT=EXHAUSTED"
mkdir -p "$d/state/judgment"
cat > "$d/state/judgment/economy-1-T-G.md" <<'J'
OBSERVABLE:   DEFERRED — pool exhausted
RAN:          nothing — no model ran
READ:         nothing — no transcript
BRIEF-ERRORS: brief assumes a model is reachable
NEXT:         wait for the free-tier window to reopen
J
block_g="$(FLEET="$d" emit_session_report "T-G" "economy-1" "$BR" "$WT" "$R" "$BASE" \
              "minimax-m3-free" "EXHAUSTED" "0" "README.md" "BLOCKED" "$OUTLOG")"
has "$block_g" "OBSERVABLE:   DEFERRED — pool exhausted" "g1 EXHAUSTED path: judgment fields still flow"
no   "$block_g" "MODEL SELF-REPORT BLOCK" "g2 EXHAUSTED path: no spurious kept section"
# Validator passes.
report_g="$d/state/reports/economy-1-T-G.md"
bash "$SRC/check-session-report.sh" "$report_g" >/dev/null 2>&1 && ok "g3 EXHAUSTED path: derived block is validator-clean" \
  || bad "g3 EXHAUSTED path: derived block FAILS the validator"
rm -rf "$d"

rm -f "$EXTRACT_HELPER"

echo
echo "--- session-report-wire: $PASS passed, $FAIL failed ---"
[ "$FAIL" -eq 0 ] || exit 1
echo "ALL SESSION-REPORT-WIRE TESTS PASS"