"""Author-independent acceptance gate for the unified event ledger (CG_PLAN_v2 §3).

This file is the CONTRACT for the ledger-schema unit. It is written from the spec,
before implementation, by a different actor than the implementer (CG_PLAN_v2 §4/§7b).

RULES:
  * Do NOT edit this file to make it pass. Implement `charon.event_ledger` to satisfy it.
  * If an API name here is genuinely wrong, propose the change in the issue thread and get
    it agreed FIRST — never weaken or delete an assertion.

Done = `pytest tests/ledger/test_event_schema.py -q` exits 0.
It is expected to be RED until the unit is implemented (that is the red-first proof).
"""

import pytest

# The unit must provide this module. These imports failing IS the initial red state.
from charon.event_ledger import Event, EventLedger

# Every event row must carry these (CG_PLAN_v2 §3).
REQUIRED_FIELDS = {
    "event_id", "ts", "unit_id",
    "actor_provider", "actor_model", "actor_fingerprint",
    "event_kind", "target_unit_id",
    "cost_usd", "tokens_in", "tokens_out", "wall_clock_ms",
    "outcome_class", "defect_class", "escape_stage",
}


def _mk(**over):
    base = dict(
        unit_id="U1", actor_provider="prov_a", actor_model="model_x",
        actor_fingerprint="fp_deadbeef", event_kind="original",
        cost_usd=1.0, tokens_in=10, tokens_out=20, wall_clock_ms=1234,
        outcome_class="quality_pass",
    )
    base.update(over)
    return base


def test_event_carries_all_required_fields():
    ev = Event(**_mk())
    for f in REQUIRED_FIELDS:
        assert hasattr(ev, f), f"Event missing required field: {f}"


def test_roundtrip_persists_model_and_fingerprint(tmp_path):
    led = EventLedger(tmp_path / "events")
    eid = led.record(**_mk(actor_model="model_x", actor_fingerprint="fp_1"))
    # A FRESH instance must read it back -> durable, cross-instance (not in-memory only).
    got = EventLedger(tmp_path / "events").get(eid)
    assert got.actor_model == "model_x"
    assert got.actor_fingerprint == "fp_1"


def test_treasury_groups_cost_by_actor_pair(tmp_path):
    led = EventLedger(tmp_path / "events")
    led.record(**_mk(unit_id="U1", actor_provider="a", actor_model="x", cost_usd=1.0))
    led.record(**_mk(unit_id="U2", actor_provider="b", actor_model="y", cost_usd=2.0))
    t = led.treasury()  # {(provider, model): total_cost_usd}
    assert t[("a", "x")] == pytest.approx(1.0)
    assert t[("b", "y")] == pytest.approx(2.0)


def test_blame_charges_remediation_back_to_origin_actor(tmp_path):
    led = EventLedger(tmp_path / "events")
    # cheap model does U1 originally
    led.record(**_mk(unit_id="U1", actor_provider="a", actor_model="cheap",
                     actor_fingerprint="f1", event_kind="original", cost_usd=0.10))
    # a pricier model later fixes U1
    led.record(**_mk(unit_id="F1", target_unit_id="U1", actor_provider="b",
                     actor_model="pricey", actor_fingerprint="f2",
                     event_kind="remediation", cost_usd=0.40,
                     defect_class="implementation", escape_stage="production"))
    blame = led.blame()  # {(provider, model): amortized_cost_to_correct}, keyed by ORIGIN actor
    # §1: origin eats original + every later fix; the fixer is not blamed.
    assert blame[("a", "cheap")] == pytest.approx(0.50)
    assert blame.get(("b", "pricey"), 0.0) == pytest.approx(0.0)


def test_operational_outcomes_are_not_gradable(tmp_path):
    led = EventLedger(tmp_path / "events")
    led.record(**_mk(unit_id="U1", outcome_class="funding", cost_usd=0.0))
    led.record(**_mk(unit_id="U2", outcome_class="ratelimit", cost_usd=0.0))
    led.record(**_mk(unit_id="U3", outcome_class="unavailable", cost_usd=0.0))
    # §2: funding / ratelimit / unavailable are ops/treasury events, never a quality grade.
    assert led.gradable_events() == []


def test_quality_outcome_is_gradable(tmp_path):
    led = EventLedger(tmp_path / "events")
    led.record(**_mk(unit_id="U1", outcome_class="quality_pass"))
    assert len(led.gradable_events()) == 1
