#!/usr/bin/env python3
"""Render docs/REVIEW-LOG.md from the per-ticket fragments in docs/review-log/.

The shared review log used to be hand-appended by every ticket, which produced a
textual merge conflict whenever two tickets landed a note in parallel. Each ticket
now owns one fragment file `docs/review-log/<id>.md`; this script concatenates the
fragments — in a stable lexical order — into the generated rollup docs/REVIEW-LOG.md.

Usage:
    python3 tools/render_review_log.py            # (re)write docs/REVIEW-LOG.md
    python3 tools/render_review_log.py --check     # exit non-zero if the rollup is stale

Stdlib-only by design (the privileged core carries no third-party deps).
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
FRAGMENT_DIR = REPO_ROOT / "docs" / "review-log"
OUTPUT_PATH = REPO_ROOT / "docs" / "REVIEW-LOG.md"

# The README documents the convention; it is not a review entry.
EXCLUDED = {"readme.md"}

SECTION_SEP = "\n\n---\n\n"

HEADER = """\
# Charon — Review Log

One entry per significant change: reviewer, charge, key findings, and the
author's per-finding reconciliation (accept/reject + why). Reviewers are
XREF-class — they flag, they do not vote or veto. The author reconciles against
physics and records it here.

<!-- DO NOT EDIT — generated by tools/render_review_log.py from docs/review-log/*.
     Add your note as a new fragment docs/review-log/<id>.md; never edit another
     ticket's fragment or this rollup. Re-render with:
         python3 tools/render_review_log.py -->"""


def fragment_paths(fragments_dir: Path) -> list[Path]:
    """Return the fragment files in a stable (lexical) order, excluding the README."""
    return sorted(
        p
        for p in fragments_dir.glob("*.md")
        if p.name.lower() not in EXCLUDED
    )


def render(fragments_dir: Path) -> str:
    """Render the full rollup text from the fragments in *fragments_dir*."""
    bodies = [
        p.read_text(encoding="utf-8").strip() for p in fragment_paths(fragments_dir)
    ]
    if not bodies:
        return HEADER + "\n"
    return HEADER + "\n\n" + SECTION_SEP.join(bodies) + "\n"


def check(fragments_dir: Path, output_path: Path) -> bool:
    """Return True iff *output_path* already equals the freshly rendered rollup."""
    expected = render(fragments_dir)
    try:
        actual = output_path.read_text(encoding="utf-8")
    except FileNotFoundError:
        return False
    return actual == expected


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero if docs/REVIEW-LOG.md is stale vs the fragments",
    )
    args = parser.parse_args(argv)

    if args.check:
        if check(FRAGMENT_DIR, OUTPUT_PATH):
            return 0
        print(
            "docs/REVIEW-LOG.md is stale; re-run `python3 tools/render_review_log.py`",
            file=sys.stderr,
        )
        return 1

    OUTPUT_PATH.write_text(render(FRAGMENT_DIR), encoding="utf-8")
    print(f"wrote {OUTPUT_PATH.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
